### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by pann-vandet** [ksonod/deep_learning_with_python#1]
Dear ksonod,

I tried to implement **chap3-3_regression_house_prices** code section and I got an error:  
**TypeError: 'int' object is not iterable**. 
But yours is working. It's grateful If you could show me what happened.

**Comment by ksonod** [comment]
Hello, pann-vandet

> **TypeError: 'int' object is not iterable**.

I'm not sure in which part you got this error, but I realized that there was a simple mistake in names. I mixed up train_labels and train_targets even though they were essentially the same. I got errors because of this simple mistake. Therefore, I corrected them. After this correction, I ran all the codes on this notebook, and everything works now. I created a new branch. https://github.com/ksonod/deep_learning_with_python/blob/fixed_error/chap3-3_regression_house_prices.ipynb

**Comment by pann-vandet** [comment]
Dear Ksonod,

Thank you very much for your reply.
Now I figured out of my code mistake.


Best regards,
Vandet
[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/17/20,
07:54:15 PM
